### ISSUE TITLE
Memoria.ffpr.cfg won't show?

### ISSUE THREAD

**Issue by bambi-xiv** [Albeoris/Memoria.FFPR#16]
Sorry to bother again..but seems i have a little problem here. I used your tool with my old pc (Asus) and it worked perfectly.
Yesterday i get a Lenovo Computer and i've start to re- installing all my games, included memoria.

Unfortunately, when i unzip the file and load the game it seems it won't create the memoria.cfg and i really don't know what may be the reason.. i hope you can help me, thanks alot.

**Comment by xanderglz** [comment]
This issue sounds too similar to mine. I tried the latest versions of BepInEx+Memoria FFPR. Since I'm playing FF2 I assume the correct file was FF2 archive. I try to run it and this is the error message it appears after trying to launch the exe:
[Screenshot](https://media.discordapp.net/attachments/866169178778894366/877184009111760976/unknown.png)

I looked into the config folder and Theres a Bepinex.cfg file, but no memoria.ff2pr.cfg and it made me think the lack of such config file had something to do with the executable not running. Maybe I can confirm my theory if there's a vanilla/untouched ff2pr.cfg file to download somewhere so I can put it in the right location.

**Comment by Albeoris** [comment]
Hey guys, please, share logs:
\FINAL FANTASY II PR\BepInEx\LogOutput.log

**Comment by Albeoris** [comment]
> Este artículo trata sobre el Error 0xc0000022, también conocido como Error 0xc0000022 y que significa Permisos incorrectos para un archivo en particular.

Judging by the description, you do not have enough rights to write to the game directory.

Most likely, you are using a user with reduced rights, disabled writing to disk in Windows Defender settings, or disabled writing to the game directory.
